name: 'Deploy to Netlify'

on:
  push:
    branches:
      - main
    

jobs:
  deploy:
    name: 'Deploy to Netlify'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.MY_NETLIFY_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true